/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader?{\"esModule\":false}!./style.css";
import _asset from "!url-loader?{\"esModule\":false}!./decrement.svg";
import _asset2 from "!url-loader?{\"esModule\":false}!./increment.svg";
import _asset3 from "!url-loader?{\"esModule\":false}!./settings.svg";
import _asset4 from "!url-loader?{\"esModule\":false}!./toggle.svg";
export const resources = {
  "userscript.js": _js,
  "style.css": _css,
  "decrement.svg": _asset,
  "increment.svg": _asset2,
  "settings.svg": _asset3,
  "toggle.svg": _asset4,
};
