/* generated by pull.js */
import _js from "./_userscript.js";
import _css from "!css-loader?{\"esModule\":false}!./style.css";
export const resources = {
  "userscript.js": _js,
  "style.css": _css,
};
