/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader?{\"esModule\":false}!./style.css";
import _asset from "!url-loader?{\"esModule\":false}!./folder.svg";
export const resources = {
  "userscript.js": _js,
  "style.css": _css,
  "folder.svg": _asset,
};
