/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "Hide watermark",
  "description": "Hides the small sprite watermark shown in the top-left corner of the block workspace.",
  "tags": ["new"],
  "enabledByDefault": true,
  "dynamicDisable": true,
  "credits": [
    {
      "name": "Clyain",
      "link": "https://github.com/Clyain"
    }
  ],
  "userstyles": [
    {
      "url": "userstyle.css"
    }
  ]
};
export default manifest;
