/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "Build from existing blocks",
  "description": "Adds a \"Build from existing blocks\" button to the custom block editor so you can quickly fill in a block definition from an existing custom block in the current sprite (or all sprites).",
  "tags": ["new"],
  "credits": [
    {
      "name": "Clyain",
      "link": "https://github.com/Clyain"
    }
  ],
  "enabledByDefault": false,
  "dynamicDisable": true,
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "userstyle.css"
    }
  ]
};
export default manifest;
