/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader?{\"esModule\":false}!./userscript.css";
export const resources = {
  "userscript.js": _js,
  "userscript.css": _css,
};
