/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader?{\"esModule\":false}!./search-bar.css";
export const resources = {
  "userscript.js": _js,
  "search-bar.css": _css,
};
