/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "dynamicEnable": true,
  "dynamicDisable": true,
  "name": "FPS counter",
  "description": "Adds an FPS counter above the stage. It will display real-time FPS during runtime.",
  "tags": ["new"],
  "credits": [
    {
      "name": "Tacodiva",
      "link": "https://github.com/Tacodiva"
    }
  ],
  "enabledByDefault": false,
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "style.css"
    }
  ]
};
export default manifest;
