/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader?{\"esModule\":false}!./style.css";
import _asset from "!url-loader?{\"esModule\":false}!./300cats.svg";
import _asset2 from "!url-loader?{\"esModule\":false}!./cat.svg";
export const resources = {
  "userscript.js": _js,
  "style.css": _css,
  "300cats.svg": _asset,
  "cat.svg": _asset2,
};
