/* generated by pull.js */
import _js from "./userscript.js";
import _asset from "!url-loader?{\"esModule\":false}!./mute.svg";
export const resources = {
  "userscript.js": _js,
  "mute.svg": _asset,
};
