/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "Desktop project page button",
  "description": "Shows the \"See Project Page\" button in the editor menu bar even when the community / project-page UI is otherwise hidden. Intended for the desktop app, so you can switch to the project view at any time.",
  "tags": ["new","danger"],
  "enabledByDefault": false,
  "dynamicDisable": true,
  "credits": [
    {
      "name": "Clyain",
      "link": "https://github.com/Clyain"
    }
  ]
};
export default manifest;
