/* generated by pull.js */

// This addon ships no userstyles and no userscript on purpose.
//
// The button it controls has to be rendered by React — it is a conditional render inside
// src/components/menu-bar/menu-bar.jsx, so a userstyle cannot reveal it (when the flag is off
// the <CommunityButton> is never created and there is nothing in the DOM to style).
//
// Instead, the menu bar reads this addon's enabled state straight out of the addon settings
// store (SettingsStore.getAddonEnabled, see src/components/menu-bar/menu-bar.jsx), and
// re-renders when it changes. The addon itself therefore only has to exist — its enabled flag
// *is* the switch, and its card on the addon settings page *is* the toggle.
//
// `resources` is still exported because AddonRunner assigns `this.resources = mod.resources`
// unconditionally (src/addons/api.js).
export const resources = {};
