/* generated by pull.js */
/* No ! it's generated by AI from Scratch Addons!!! */
const manifest = {
  "name": "Recolor custom blocks",
  "description": "Adds an option to choose a custom color when creating a block. This feature works by adding the color code or category name at the beginning of the block's label.",
  "credits": [
    {
      "name": "FlamedDogo99",
      "link": "https://github.com/FlamedDogo99"
    }
  ],
  "tags": ["new"],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "userstyle.css"
    }
  ],
  "settings": [
    {
      "name": "Hide color prefixes",
      "id": "hide-color-prefix",
      "type": "boolean",
      "default": true,
      "dynamic": true
    }
  ],
  "dynamicDisable": true,
  "enabledByDefault": false
};
export default manifest;
