/* generated by pull.js */
/* No ! it's generated by AI from Scratch Addons!!! */
import _js from "./userscript.js";
import _css from "!css-loader?{\"esModule\":false}!./userstyle.css";
import _asset from "!url-loader?{\"esModule\":false}!./assets/checkmark.svg";
export const resources = {
  "userscript.js": _js,
  "userstyle.css": _css,
  "assets/checkmark.svg": _asset,
};
