/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader?{\"esModule\":false}!./style.css";
import _asset from "!url-loader?{\"esModule\":false}!./icons/close.svg";
import _asset2 from "!url-loader?{\"esModule\":false}!./icons/debug.svg";
import _asset3 from "!url-loader?{\"esModule\":false}!./icons/delete.svg";
import _asset4 from "!url-loader?{\"esModule\":false}!./icons/download-white.svg";
import _asset5 from "!url-loader?{\"esModule\":false}!./icons/error.svg";
import _asset6 from "!url-loader?{\"esModule\":false}!./icons/logs.svg";
import _asset7 from "!url-loader?{\"esModule\":false}!./icons/performance.svg";
import _asset8 from "!url-loader?{\"esModule\":false}!./icons/play.svg";
import _asset9 from "!url-loader?{\"esModule\":false}!./icons/step.svg";
import _asset10 from "!url-loader?{\"esModule\":false}!./icons/subthread.svg";
import _asset11 from "!url-loader?{\"esModule\":false}!./icons/threads.svg";
import _asset12 from "!url-loader?{\"esModule\":false}!./icons/warning.svg";
import _asset13 from "!url-loader?{\"esModule\":false}!./icons/variables.svg";
import _asset14 from "!url-loader?{\"esModule\":false}!./icons/favorites.svg";
import _asset15 from "!url-loader?{\"esModule\":false}!./icons/favorited.svg";

export const resources = {
  "userscript.js": _js,
  "style.css": _css,
  "icons/close.svg": _asset,
  "icons/debug.svg": _asset2,
  "icons/delete.svg": _asset3,
  "icons/download-white.svg": _asset4,
  "icons/error.svg": _asset5,
  "icons/logs.svg": _asset6,
  "icons/performance.svg": _asset7,
  "icons/play.svg": _asset8,
  "icons/step.svg": _asset9,
  "icons/subthread.svg": _asset10,
  "icons/threads.svg": _asset11,
  "icons/warning.svg": _asset12,
  "icons/variables.svg": _asset13,
  "icons/favorites.svg": _asset14,
  "icons/favorited.svg": _asset15
};
