/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader?{\"esModule\":false}!./arrows.css";
export const resources = {
  "userscript.js": _js,
  "arrows.css": _css,
};
