/* generated by pull.js */
const manifest = {
    "editorOnly": true,
    "name": "README",
    "description": "Edit project documentation as a special workspace comment. Open it from the toolbox button in the top-right corner of the workspace; right-click empty workspace area to add a README.",
    "credits": [
        {
            "name": "Clyain",
            "link": "https://github.com/Clyain"
        }
    ],
    "tags": [
        "new"
    ],
    "enabledByDefault": true,
    "userscripts": [
        {
            "url": "userscript.js"
        }
    ],
    "userstyles": [
        {
            "url": "userstyle.css"
        }
    ]
};
export default manifest;
