/* generated by pull.js */
import _css from "!css-loader?{\"esModule\":false}!./menu-icons.css";
import _css2 from "!css-loader?{\"esModule\":false}!./menu-labels.css";
import _css3 from "!css-loader?{\"esModule\":false}!./small-window-icons.css";
import _css4 from "!css-loader?{\"esModule\":false}!./keep-labels-small-windows.css";
export const resources = {
  "menu-icons.css": _css,
  "menu-labels.css": _css2,
  "small-window-icons.css": _css3,
  "keep-labels-small-windows.css": _css4,
};
