/* generated by pull.js */
import _js from "./userscript.js";
import _asset from "!url-loader?{\"esModule\":false}!./icon--close.svg";
export const resources = {
  "userscript.js": _js,
  "icon--close.svg": _asset,
};
