/* generated by pull.js */
import _js from "./fix-share-the-love.js";
import _css from "!css-loader?{\"esModule\":false}!./stageleft.css";
export const resources = {
  "fix-share-the-love.js": _js,
  "stageleft.css": _css,
};
