/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader?{\"esModule\":false}!./userstyle.css";
import _css2 from "!css-loader?{\"esModule\":false}!./hover.css";
import _asset from "!url-loader?{\"esModule\":false}!./loud.svg";
import _asset2 from "!url-loader?{\"esModule\":false}!./mute.svg";
import _asset3 from "!url-loader?{\"esModule\":false}!./quiet.svg";
export const resources = {
  "userscript.js": _js,
  "userstyle.css": _css,
  "hover.css": _css2,
  "loud.svg": _asset,
  "mute.svg": _asset2,
  "quiet.svg": _asset3,
};
