/* generated by pull.js */
import _css from "!css-loader?{\"esModule\":false}!./sprites.css";
import _css2 from "!css-loader?{\"esModule\":false}!./costumes.css";
import _css3 from "!css-loader?{\"esModule\":false}!./sounds.css";
export const resources = {
  "sprites.css": _css,
  "costumes.css": _css2,
  "sounds.css": _css3,
};
